package com.example.kappapridesms;

import android.app.AlertDialog;
import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.os.Bundle;
import android.view.View;

import androidx.fragment.app.DialogFragment;


/**
 * Displays a forward dialog if a user wants to forward a message.
 * This class extends the DialogFragment class that is available in
 * in the Android API.
 *
 * This dialog is opened when the user first selects the forward option from
 * the options menu in the toolbar of Message Activity and selects a message.
 * <p>
 *     Contains two private attributes:
 *     <p>
 *         - m_dialogListener
 *     </p>
 *     <p>
 *         - m_forwardContent
 *     </p>
 * </p>
 * <p>
 *     Contains six public methods:
 *     <p>
 *         - onCreate()
 *     </p>
 *     <p>
 *         - onAttach()
 *     </p>
 *     <p>
 *         - onCreateDialog()
 *     </p>
 *     <p>
 *         - onClick()
 *     </p>
 *     <p>
 *         - onCLick()
 *     </p>
 *     <p>
 *         - getForwardContent()
 *     </p>
 * </p>
 *
 * @author Nathan Beck
 */
public class ForwardDialog extends DialogFragment
{
    /**
     * The ForwarddialogListener that is subscribed to handle onClick events.
     */
    private ForwardDialogListener m_dialogListener;

    /**
     * The corresponding view of this ForwardDialog
     */
    private View m_forwardContent;

    /**
     * ForwardDialogListener provides an interface for those classes subscribing
     * to handle onClick events generated by this ForwardDialog.
     *
     * @author Nathan Beck
     */
    public interface ForwardDialogListener
    {
        /**
         * The method called on the ForwardDialogListener upon clicking the positive button
         */
        void onForwardPositiveClickListener();

        /**
         * The method called on the ForwardDialogListener upon clicking the negative button
         */
        void onForwardNegativeClickListener();
    }

    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
    }

    /**
     * Attaches this AddContactDialog to a given context, registering this contact
     * as a ContactDialogListener for its button events.
     *
     * @param context The context to attach this AddContactDialog.
     */
    @Override
    public void onAttach(Context context)
    {
        super.onAttach(context);

        try
        {
            // Instantiate the NoticeDialogListener so we can send events to the host
            m_dialogListener = ((MessageActivity) context).getMessageFragment();;
        }catch(ClassCastException e)
        {
            // Context does not implement ForwardDialogListener
            throw new ClassCastException("Context instance does not implement ForwardDialogListener");
        }
    }

    /**
     * Creates the viewable dialog and sets the actions to be taken on button clicks.
     * Here, the listener subscribed to this ForwardDialog will be called via an
     * OnClick event.
     *
     * @param savedInstanceState The state saved between lifecycle stage changes.
     * @return The constructed Dialog associated with this AddContactDialog.
     */
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState)
    {
        // Get an AlertDialog.Builder to construct this dialog.
        AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(getActivity());

        // Set the content (View) and the title for this dialog.
        dialogBuilder.setTitle("Forward");
        m_forwardContent = requireActivity().getLayoutInflater().inflate(R.layout.forward_view, null);
        dialogBuilder.setView(m_forwardContent);

        // Specify the onClick functionality for this dialog.
        dialogBuilder.setPositiveButton("Forward", new DialogInterface.OnClickListener() {
            /**
             * Method that is called when the button in the dialog is clicked.
             *
             * @param dialog The dialog that received the click.
             * @param which Denotes which button was clicked.
             */
            @Override
            public void onClick(DialogInterface dialog, int which)
            {
                m_dialogListener.onForwardPositiveClickListener();
                dismiss();
            }
        });
        dialogBuilder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
            /**
             * Method that is called when the button in the dialog is clicked.
             *
             * @param dialog The dialog that received the click.
             * @param which Denotes which button was clicked.
             */
            @Override
            public void onClick(DialogInterface dialog, int which)
            {
                m_dialogListener.onForwardNegativeClickListener();
                dismiss();
            }
        });

        return dialogBuilder.create();
    }

    /**
     * This method retrieves the view associated with this ForwardDialog.
     *
     * @return The View associated with this ForwardDialog.
     */
    public View getForwardContent()
    {
        return m_forwardContent;
    }
}
